version: "3"
services:
  nginx:
    build: ${HOMEDIR}
    image: learn-nginx:latest
    container_name: trynginx
    ports:
     - 8443:443
     - 8080:80
    volumes:
     - ${HOMEDIR}:/root/workdir
    entrypoint: "bash /root/daemon.sh"
